![veribilimisureci](../images/veri_manipulasyonu/veri_bilimi_sureci.jpg)

### *Introduction to Numpy*
- *Numpy: Numerical Python*
- *Bilimsel hesaplamalar için kullanılır.*
- *Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.*
- *Temelleri 1995'te (matrix-sig, Guido Van Rossum) atılmış nihai olarak 2005 (Travis Oliphant) yılında hayata geçmiştir.*
- *Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.*
- *Listelerde her bir eleman için ayrı bilgi tutmak gerekirken Numpy'da ise sabit tek bir bilgi tutuluyor*

In [2]:
# Numpy kütüphanesini çağıralım
import numpy as np

### *Creating a Numpy Array*

In [3]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

print(type(a))

print(a * b)

<class 'numpy.ndarray'>
[ 2  6 12 20]


In [4]:
import numpy as np

# dtype: array veri tipi
np.array([3.14, 4, 2, 13], dtype= "int")

array([ 3,  4,  2, 13])

### *Creating an array from scratch*

In [5]:
import numpy as np

# zeros(): sıfırlardan oluşan dizi oluşturur
npZeros = np.zeros(10, dtype= int) # 10 tane integer 0'dan oluşuyor
print("npZeros: \n", npZeros)
print("*" * 40)

# ones(): birlerden oluşan dizi oluşturur
npOnes = np.ones((3,5), dtype=int) # 3 satır 5 sütundan oluşan birim matris (hepsi birlerden oluşan) oluşuyor
print("npOnes: \n", npOnes)
print("*" * 40)

# full(): 1 dışında başka bir sayıyla doldurmak istiyorum diyorsanız bunu kullanın
npFull = np.full((3,5), 2) # 3 satır 2 sütun var ve hepsinde 2 yazıyor
print("npFull: \n", npFull)
print("*" * 40)

# arange(): Verilen aralıkta doğrusal bir dizi oluşturur
npArange = np.arange(0, 31, 3) # 0'dan 31'e kadar üçer üçer artan bir dizi
print("npArange: \n", npArange)
print("*" * 40)

npZeros: 
 [0 0 0 0 0 0 0 0 0 0]
****************************************
npOnes: 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
****************************************
npFull: 
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
****************************************
npArange: 
 [ 0  3  6  9 12 15 18 21 24 27 30]
****************************************


In [6]:
import numpy as np

# linspace(): Belli iki değer arasında belirli sayı kadar değer oluşturur
npLinspace = np.linspace(0, 1, 10) # 0-1 arasında 10 tane değer oluşuyor
print("npLinspace: \n", npLinspace)
print("*" * 40)

# random.normal(): İstediğimiz bir dağılım özelliği taşıyacak şekilde arrayler oluşturur
npRandNor = np.random.normal(10, 4, (3, 4)) # Ortalaması 10, standart sapması 4 olan 3'e 4'lük bir matris oluşturdu
print("npRandNor: \n", npRandNor)
print("*" * 40)

# random.randint(): Belirli iki değer arasında rastgele dizi oluşturur
npRandRan = np.random.randint(0, 10, (3, 3)) # 0-10 arasında rastgele 3'e 3'lük bir matris oluşturur
print("npRandRan: \n", npRandRan)
print("*" * 40)

npLinspace: 
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
****************************************
npRandNor: 
 [[ 3.34679205  6.24834606 10.92842964  7.84200351]
 [15.47809857 13.33874519 13.00141068  9.91638037]
 [ 8.64387767  0.9606399  12.44539207  8.53121361]]
****************************************
npRandRan: 
 [[5 7 6]
 [4 1 5]
 [9 0 8]]
****************************************


### *Numpy Array Attributes*
- *ndim: boyut sayısı*
- *shape: boyut bilgisi*
- *size: toplam eleman sayısı*
- *dtype: array veri tipi*

In [9]:
import numpy as np

z = np.random.randint(10, size= (3,5))

print("Boyut sayısı:", z.ndim)
print("Boyut bilgisi:", z.shape)
print("Toplam eleman sayısı:", z.size)
print("Array veri tipi:", z.dtype)

Boyut sayısı: 2
Boyut bilgisi: (3, 5)
Toplam eleman sayısı: 15
Array veri tipi: int32


### *Reshaping*

In [20]:
import numpy as np

# Verilen aralıkta doğrusal bir dizi oluşturalım
arn = np.arange(1,10)
print(" arn: \n", arn)
print("Boyut sayısı:", arn.ndim)
print("Boyut bilgisi:", arn.shape)

# reshape() ile yeniden şekillendirelim ve 3'e 3'lük bir matris yapalım
new_arn = np.arange(1,10).reshape((3,3))
print("\n new_arn: \n", new_arn)
print("Boyut sayısı:", new_arn.ndim)
print("Boyut bilgisi:", new_arn.shape)

 arn: 
 [1 2 3 4 5 6 7 8 9]
Boyut sayısı: 1
Boyut bilgisi: (9,)

 new_arn: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Boyut sayısı: 2
Boyut bilgisi: (3, 3)


### *Concantenation*
- *axis: eksen*
- *axis= 0 Satır ekseni*
- *axis= 1 Sütun ekseni*

In [24]:
import numpy as np

# Tek boyutta birleştirme
x = np.array([1,2,3])
y = np.array([4,5,6])

xy = np.concatenate([x, y])
print(xy, "\n")

# İki boyutta birleştirme
a = np.array([[1,2,3], 
              [4,5,6]])

# Satır bazında birleştirme yapalım
satir = np.concatenate([a,a])
print(satir, "\n")

# Sütun bazında birleştirme yapalım
sutun = np.concatenate([a,a], axis= 1)
print(sutun)

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### *Splitting*

In [32]:
import numpy as np

# Tek Boyutlu Array Ayırma
x = np.array([1,2,3,99,99,3,2,1])

# Dizimizi 3 parçaya ayıralım. İlk parçası 3'e kadar, 2.parça 5'e kadar olanlardan boşta kalanları seçilsin diyoruz.
a, b, c = np.split(x, [3,5])
print("a:", a)
print("b:", b)
print("c:", c)

a: [1 2 3]
b: [99 99]
c: [3 2 1]


In [36]:
import numpy as np

# İki Boyutlu Array Ayırma
m = np.arange(16).reshape(4,4)
print("m: \n", m, end='\n\n')

# vsplit: dikey olarak ayırıyor
ust, alt = np.vsplit(m, [2])
print("ust: \n", ust, end='\n\n')
print("alt: \n", alt)

m: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

ust: 
 [[0 1 2 3]
 [4 5 6 7]]

alt: 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [39]:
import numpy as np

# İki Boyutlu Array Ayırma
m = np.arange(16).reshape(4,4)
print("m: \n", m, end='\n\n')

# hsplit: yatay olarak ayırıyor
sol, sag = np.hsplit(m, [2])
print("sol: \n", sol, end='\n\n')
print("sağ: \n", sag)

m: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

sol: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

sağ: 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### *Sorting*

In [49]:
import numpy as np

# Tek boyutlu array sıralama
v = np.array([2,1,4,3,5])
print("Tek boyutlu array: \n", v, end="\n\n")

vs = np.sort(v)
print("Tek boyutlu sıralama: \n", vs, end="\n\n")

# İki boyutlu array sıralama
m = np.random.normal(20,5, (3,3))
print("İki boyutlu array: \n", m, end="\n\n")

ms = np.sort(m, axis= 1)
print("İki boyutlu sıralama: \n", ms)

Tek boyutlu array: 
 [2 1 4 3 5]

Tek boyutlu sıralama: 
 [1 2 3 4 5]

İki boyutlu array: 
 [[27.68963846 12.92301052 21.93059795]
 [24.83057451 24.40878577 12.72871819]
 [30.77772518 18.49976317 19.4406841 ]]

İki boyutlu sıralama: 
 [[12.92301052 21.93059795 27.68963846]
 [12.72871819 24.40878577 24.83057451]
 [18.49976317 19.4406841  30.77772518]]


### *Accessing Elements with Index*

In [56]:
import numpy as np

a = np.random.randint(12, size=6)

print(a)
print(a[0])
print(a[-1])

a[0] = 100
print(a)

[ 4  9 10 11  7  8]
4
8
[100   9  10  11   7   8]


In [63]:
import numpy as np

m = np.random.randint(12, size= (3,5))
print(m, end="\n\n")
print(m[2,4], end="\n\n")

m[1,3] = 97
print(m)

[[ 1  1 10  5  3]
 [ 0  3 11  6  8]
 [ 3  8  4  1  0]]

0

[[ 1  1 10  5  3]
 [ 0  3 11 97  8]
 [ 3  8  4  1  0]]


### *Accessing elements with slicing (Array Subset Operations)*

In [71]:
# Slicing ile Array alt kümesine erişmek
import numpy as np

# 20-30 aralığında doğrusal bir dizi oluşturalım
a = np.arange(20,30)
print("Doğrusal dizi:", a, end="\n\n")
print("Dizinin ilk 3 elemanı:", a[0:3])

# 2.indexten 8.index'e kadar üçer üçer artacak şekilde olanlara erişelim
print("Özel alt küme:", a[2:8:2])

Doğrusal dizi: [20 21 22 23 24 25 26 27 28 29]

Dizinin ilk 3 elemanı: [20 21 22]
Özel alt küme: [22 24 26]


In [77]:
import numpy as np

# İki boyutlu slice işlemleri
m = np.random.randint(10, size= (5,5))
print(m, end="\n\n")
print("1.sütundaki tüm satırlar: ", m[:,1])
print("3.satırdaki tüm sütunlar: ", m[3,:])
print("\n0.satırdan 2.satıra ve 0.sütundan 3.sütuna kadar olanlar: \n", m[0:2, 0:3])


[[3 9 3 2 4]
 [9 6 7 1 4]
 [8 4 9 8 6]
 [6 2 6 2 3]
 [0 7 4 2 9]]

1.sütundaki tüm satırlar:  [9 6 4 2 7]
3.satırdaki tüm sütunlar:  [6 2 6 2 3]

0.satırdan 2.satıra ve 0.sütundan 3.sütuna kadar olanlar: 
 [[3 9 3]
 [9 6 7]]


### *Fancy Index*
*Daha ileri düzeyde elemanlara erişmeyi sağlıyor.*

In [83]:
import numpy as np

v = np.arange(0, 30, 3)
print(v)

# Indexlere erişim ile
print("\nIndexlere normal erişim ile 1,3,5.indexleri getirelim:")
print([v[1], v[3], v[5]])

# Fancy Index ile
al_getir = [1, 3, 5]
print("\nFancy Index ile 1,3,5.indexleri getirelim:")
print(v[al_getir])

[ 0  3  6  9 12 15 18 21 24 27]

Indexlere normal erişim ile 1,3,5.indexleri getirelim:
[3, 9, 15]

Fancy Index ile 1,3,5.indexleri getirelim:
[ 3  9 15]


In [90]:
import numpy as np

# İki boyutta Fancy Index
m = np.arange(9).reshape((3,3))
print("İki boyutlu dizi: \n",m)

satir = np.array([0,1])
sutun = np.array([1,2])
print("0-1.Satırlar arası ile 1-2.Sütunlar arasındaki elemanlar: ", m[satir, sutun])

İki boyutlu dizi: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
0-1.Satırlar arası ile 1-2.Sütunlar arasındaki elemanlar:  [1 5]


In [94]:
import numpy as np
m = np.arange(9).reshape((3,3))

# Basit index ile Fancy Index'i bir arada kullanma
print(m[0, [1,2]], end="\n\n")

# Slice ile Fancy Index'i bir arada kullanma
print(m[0:, [1,2]], end="\n\n")

[1 2]

[[1 2]
 [4 5]
 [7 8]]



### *Conditional Element Operations*

In [95]:
import numpy as np
v = np.array([1,2,3,4,5])

print(v < 3)
print(v[v < 3])
print(v[v >= 3])
print(v[v != 3])

[ True  True False False False]
[1 2]
[3 4 5]
[1 2 4 5]
[ 1  4  9 16 25]


### *Introduction to Mathematical Operations*

In [101]:
import numpy as np
v = np.array([1,2,3,4,5])

print(v - 1)
print(v + 5)
print(v * 5)
print(v / 5)
print(v**3)
print(v % 2)

[0 1 2 3 4]
[ 6  7  8  9 10]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[  1   8  27  64 125]
[1 0 1 0 1]


- *subtract(): çıkarma işlemi*
- *add(): toplama işlemi*
- *multiply(): çarpma işlemi*
- *divide(): bölme işlemi*
- *power(): üs alma işlemi*
- *mod(): bölümden kalan bulma işlemi*
- *absolute(): Mutlak değer alma işlemi*

In [110]:
import numpy as np
v = np.array([1,2,3,4,5])

print("Çıkarma: ", np.subtract(v, 1))
print("Toplama: ", np.add(v, 5))
print("Çarpma: ", np.multiply(v, 5))
print("Bölme: ", np.divide(v, 5))
print("Üs alma: ", np.power(v, 3))
print("Kalan bulma: ", np.mod(v, 2))
print("Mutlak değer alma: ", np.absolute(np.array([-3])))

Çıkarma:  [0 1 2 3 4]
Toplama:  [ 6  7  8  9 10]
Çarpma:  [ 5 10 15 20 25]
Bölme:  [0.2 0.4 0.6 0.8 1. ]
Üs alma:  [  1   8  27  64 125]
Kalan bulma:  [1 0 1 0 1]
Mutlak değer alma:  [3]


### *Other Mathematical Operations*

In [121]:
import numpy as np

print("Sinüs alma:", np.sin(360))
print("Cosinüs alma:", np.cos(180))

v = np.array([1,2,3])
print("Logaritma e tabanında alma:", np.log(v))
print("Logaritma 2 tabanında alma:", np.log2(v))


Sinüs alma: 0.9589157234143065
Cosinüs alma: -0.5984600690578581
Logaritma e tabanında alma: [0.         0.69314718 1.09861229]
Logaritma 2 tabanında alma: [0.        1.        1.5849625]


### *Statistical Calculations*

In [124]:
import numpy as np
v = np.array([1,2,3,4,5])

print("Ortalama: ", np.mean(v))
print("Toplam: ", v.sum())
print("En küçük değer: ", v.min())
print("En büyük değer: ", v.max())
print("Varyans: ", np.var(v))
print("Standart Sapma: ", np.std(v))

Ortalama:  3.0
Toplam:  15
En küçük değer:  1
En büyük değer:  5
Varyans:  2.0
Standart Sapma:  1.4142135623730951


### *Solving Equations with Two Unknowns with Numpy*

Örn:

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [128]:
import numpy as np

a = np.array([[5,1], [1,3]])
b = np.array([12,10])

x0, x1 = np.linalg.solve(a, b)
print("x0:", x0)
print("x1:", x1)

x0: 1.857142857142857
x1: 2.7142857142857144


### *Creating a three-dimensional array*
*np.random.randint(Rastgele üretilen sayıların olduğu aralık, size = (arka arkaya kaç tane olacağının sayısı, Satır Sayısı, Sütun Sayısı))*

In [6]:
import numpy as np

ucboyutlu1 = np.random.randint(10, size = (1,3,2))
print("Size'ı (1,3,2) olan:\n", ucboyutlu1, end="\n\n")

ucboyutlu2 = np.random.randint(10, size = (2,3,2))
print("Size'ı (2,3,2) olan:\n", ucboyutlu2, end="\n\n")

ucboyutlu3 = np.random.randint(10, size = (3,2,2))
print("Size'ı (3,2,2) olan:\n", ucboyutlu3, end="\n\n")

Size'ı (1,3,2) olan:
 [[[6 9]
  [4 4]
  [7 9]]]

Size'ı (2,3,2) olan:
 [[[2 0]
  [9 8]
  [9 0]]

 [[3 2]
  [2 7]
  [0 8]]]

Size'ı (3,2,2) olan:
 [[[7 6]
  [9 7]]

 [[6 4]
  [5 4]]

 [[1 9]
  [0 7]]]



In [7]:
import numpy as np

ucboyutlu4 = np.random.randint(10, size = (3,3,2))
print("Size'ı (3,3,2) olan:\n", ucboyutlu4, end="\n\n")

ucboyutlu5 = np.random.randint(10, size = (3,3,1))
print("Size'ı (3,3,1) olan:\n", ucboyutlu5)

Size'ı (3,3,2) olan:
 [[[2 2]
  [6 2]
  [2 4]]

 [[9 0]
  [7 9]
  [1 1]]

 [[7 0]
  [6 6]
  [2 7]]]

Size'ı (3,3,1) olan:
 [[[2]
  [9]
  [6]]

 [[9]
  [5]
  [8]]

 [[4]
  [3]
  [1]]]
